load("//:CPPVARIABLES.bzl", "DDS_CPPOPTS", "DDS_LINKOPTS", "DDS_LOCAL_DEFINES")
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "belief_evaluation",
    srcs = [
        "kahan.cpp",
        "layout_key.cpp",
        "node.cpp",
        "position.cpp",
        "rank_map.cpp",
        "renumber.cpp",
        "trick.cpp",
        "validation.cpp",
    ],
    hdrs = [
        "declarer_strategy.hpp",
        "defender_strategy.hpp",
        "kahan.hpp",
        "layout_key.hpp",
        "layout_source.hpp",
        "node.hpp",
        "position.hpp",
        "rank_map.hpp",
        "renumber.hpp",
        "trick.hpp",
        "types.hpp",
        "validation.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//library/src/lookup_tables",
        "//library/src/api:api_definitions",
        "//library/src/utility:constants",
    ],
    include_prefix = "belief_evaluation",
    copts = DDS_CPPOPTS,
    linkopts = DDS_LINKOPTS,
    local_defines = DDS_LOCAL_DEFINES,
)
